[project]
name = "rl-warehouse"
version = "0.1.0"
description = "RL Warehouse OpenEnv project"
authors = [{name = "Snipy19"}]

dependencies = [
    "fastapi",
    "uvicorn",
    "numpy",
    "openenv==0.1.13"
]

[project.scripts]
server = "server.app:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"